spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysql-db-signatures:3306/students?serverTimezone=UTC
    username: root
    password: mysql

server:
  port: 8084